### ISSUE TITLE
log file for error

### ISSUE THREAD

**Issue by weizhousjtu** [TiphaineCMartin/coMET_original#3]
> START COMET VERSION GENERIC
START READ.CONFIG
FINISH READ.CONFIG
START CHECK.CONFIG
No value for the color of info file.
 
          Parametre: color.list
No value for the supplementary file.
 
          Parametre: mydata.large.file No list of GGbio track

           Parameter: tracks.ggbio
No list of TrackViewer track

           Parameter: tracks.trackviewer
No list of TrackViewer track

           Parameter: palette.file
No user file to annotation

           Parameter: biofeat.user.file
No value for the symbol factor

           Parameter: symbol.factor
FINISH CHECK.CONFIG
TYPE DATA: file 
START CREATE.color.list
FINISH CREATE.color.list
START CREATE.SYMBOL.LIST
FINISH CREATE.SYMBOL.LIST
START RETRIEVE.DATA
START READ.FILE.MYDATA  1 
START CHECK.FORMAT.MYDATA
mydata.test  8 4 
mydata.test  MYDATA.NAME CHROMOSOME LOC MYDATA.PVAL 
mydata.format  site 
FINISH CHECK.FORMAT.MYDATA
FINISH READ.FILE.MYDATA  1 
READ  1  MYDATA file 
format site 
gbl.var$mydata.num  8 
START SET.IMAGE.PARAMETERS
font.size  9 
FINISH SET.IMAGE.PARAMETERS
START FIX.VALUES
FINISH FIX.VALUES
Ref  
START READ.FILE.COMATRIX
Format data raw 
Matrice size 8 
Matrice size 8 
START COMPUTE.CORMATRIX
Compute the correlation matrice with corr.test
FINISH COMPUTE.CORMATRIX

 Matrice size num.mydat a 8 
Matrice size row.LD  8 
Matrice size col.LD  8 
Pvalue data for correlation matrix 
Ref position  
FINISH READ.FILE.COMET
Longer of all.beta 0 
Mean beta 0 
SD beta 0 
START FIX.VALUES.GENERIC
FINISH FIX.VALUES.GENERIC
FINISH RETRIEVE.DATA
START DRAW.PLOT.COMET
START DRAW.PLOT.GRID.SETUP
START DRAW.PLOT.LINESCONNECTION
Error in unit(at, "native") : 'x' and 'units' must have length > 0

**Comment by TiphaineCMartin** [comment]
cf issue #2
